[build]
target = "wasm32-unknown-emscripten"
rustflags = [
    "-L./binaryen/lib",
    "-lbinaryen",
    "-Ctarget-feature=+bulk-memory,+nontrapping-fptoint,+simd128",
    "-Clink-arg=-sALLOW_MEMORY_GROWTH=1",
    "-Zlink-native-libraries=false",
    "-Clink-args=-sWASM_BIGINT",
]

